{"uid":"bd6d18e4e798114e","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1749820163954,"stop":1749820163981,"duration":27},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at cypress/e2e/api/createMultipleUser.js (http://dummy-url.com/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:13968:43)\n    at __init (http://dummy-url.com/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:9:58)\n    at eval (http://dummy-url.com/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:14031:3)\n    at eval (http://dummy-url.com/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:14034:3)\n    at eval (<anonymous>)\n    at <unknown> (http://dummy-url.com/__cypress/runner/cypress_runner.js:111981:23)\n    at tryCatcher (http://dummy-url.com/__cypress/runner/cypress_runner.js:1777:23)\n    at Object.gotValue (http://dummy-url.com/__cypress/runner/cypress_runner.js:6446:18)\n    at Object.gotAccum (http://dummy-url.com/__cypress/runner/cypress_runner.js:6435:25)\n    at Object.tryCatcher (http://dummy-url.com/__cypress/runner/cypress_runner.js:1777:23)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://dummy-url.com/__cypress/runner/cypress_runner.js:3456:19)\n    at Promise._then (http://dummy-url.com/__cypress/runner/cypress_runner.js:1209:17)\n    at Promise.then (http://dummy-url.com/__cypress/runner/cypress_runner.js:1102:17)\n    at runScriptsFromUrls (http://dummy-url.com/__cypress/runner/cypress_runner.js:111985:136)\n    at Object.runScripts (http://dummy-url.com/__cypress/runner/cypress_runner.js:112026:12)\n    at $Cypress.onSpecWindow (http://dummy-url.com/__cypress/runner/cypress_runner.js:41405:67)\n    at <unknown> (http://dummy-url.com/__cypress/iframes/cypress%5Ce2e%5Capi%5CcreateMultipleUser.feature?browserFamily=chromium:276:22)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":27,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"package","value":"cypress.e2e.api.createMultipleUser.feature"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b23fe6e87d37772f","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749819751963,"stop":1749819751996,"duration":33}},{"uid":"3968d3eb9c3f658a","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749819542371,"stop":1749819542404,"duration":33}},{"uid":"10117caac3362b62","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749819406657,"stop":1749819406685,"duration":28}},{"uid":"5e1fc1776c410d95","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749819263509,"stop":1749819263527,"duration":18}},{"uid":"789d213f3adddf44","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749819143541,"stop":1749819143578,"duration":37}},{"uid":"4d0d9823dda7d5fc","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.log()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749817790991,"stop":1749817791005,"duration":14}},{"uid":"f2de654f76b83ecb","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.log()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749817751193,"stop":1749817751221,"duration":28}},{"uid":"e2e6d1ad624328dd","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.log()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749817724014,"stop":1749817724041,"duration":27}},{"uid":"f4ed0b2031fb898d","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749730191558,"stop":1749730191768,"duration":210}},{"uid":"526a8d345666dbf2","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749730078446,"stop":1749730078699,"duration":253}},{"uid":"d68e21972c8383b7","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749729094936,"stop":1749729094953,"duration":17}},{"uid":"eecf75d8a99ca4d5","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749728966590,"stop":1749728966610,"duration":20}},{"uid":"582a8db08979e19f","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749728850335,"stop":1749728850378,"duration":43}},{"uid":"311d1281a4134624","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749728842140,"stop":1749728842186,"duration":46}},{"uid":"16b5a56181eabac3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749646029014,"stop":1749646029032,"duration":18}},{"uid":"c4f334a2286f3864","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749646016398,"stop":1749646016420,"duration":22}},{"uid":"e142deb627d7f03c","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749646006653,"stop":1749646006692,"duration":39}},{"uid":"7f26fd02376d6b31","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749029557248,"stop":1749029557264,"duration":16}},{"uid":"1043413d1031c104","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749029456172,"stop":1749029456211,"duration":39}},{"uid":"625ca773f661bac7","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749028932881,"stop":1749028932898,"duration":17}},{"uid":"d6037b1909a23621","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749028923741,"stop":1749028923773,"duration":32}},{"uid":"3ef08f25bba41115","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749028876626,"stop":1749028876645,"duration":19}},{"uid":"308b5f5f14e2530a","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749028102313,"stop":1749028102519,"duration":206}},{"uid":"1d170ff07ee8525b","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749026604909,"stop":1749026604924,"duration":15}},{"uid":"d9be8c1c6be79a4d","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'createUsers')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1749026517644,"stop":1749026517680,"duration":36}},{"uid":"489db21fa6391f09","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > After is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1748593236121,"stop":1748593236136,"duration":15}},{"uid":"584894ed035a05ee","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > After is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1748593133781,"stop":1748593133810,"duration":29}}],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":[]},"source":"bd6d18e4e798114e.json","parameterValues":[]}