{"uid":"e44080b44d5e08ef","name":"Oops...we found an error preparing this test file: createMultipleUser.feature","fullName":"Oops...we found an error preparing this test file: createMultipleUser.feature","time":{},"status":"broken","statusMessage":"Oops...we found an error preparing this test file:\n\n  > cypress\\support\\e2e.js\n\n","statusTrace":"\n\nError: Build failed with 1 error:\ncypress/support/e2e.js:19:7: ERROR: Could not resolve \"@badeball/cypress-cucumber-preprocessor/commands\"\n    at failureErrorWithLog (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:1477:15)\n    at C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:946:25\n    at runOnEndCallbacks (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:1317:45)\n    at buildResponseToResult (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:944:7)\n    at C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:971:16\n    at responseCallbacks.<computed> (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:623:9)\n    at handleIncomingPacket (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:678:12)\n    at Socket.readFromStdout (C:\\Users\\aditya.itware\\Desktop\\CypresswithCucumber\\node_modules\\esbuild\\lib\\main.js:601:7)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)\n\nThis occurred while Cypress was compiling and bundling your test code. This is usually caused by:\n\n- A missing file or dependency\n- A syntax error in the file or one of its dependencies\n\nFix the error in your code and re-run your tests.","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":"createMultipleUser.feature"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","categories":[{"name":"Test defects","matchedStatuses":[]}],"tags":[]},"source":"e44080b44d5e08ef.json","parameterValues":[]}